entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
